package com.dynamo.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Book")
public class Book {

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
	@DynamoDBAttribute
	private String title;
	@DynamoDBAttribute
	private String description;
	@DynamoDBAttribute
	private String author;
	@DynamoDBAttribute
	private String publisher;
	@DynamoDBAttribute
	private String year;
	@DynamoDBAttribute
	private String isbn;
}